version: '3'

services:

  app:
    build: .
    container_name: micro-codeflix
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    tty: true
