import Page from "../components/Page";

const Home: React.FunctionComponent = (props) => {
    return (
        <Page>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus fringilla, est sit amet euismod aliquam, leo purus faucibus est, vitae tempus lacus felis vel felis. Sed imperdiet congue eros ut consequat. Nulla ac posuere eros. Pellentesque ac auctor mauris. Sed fringilla erat in tellus laoreet, id porta eros molestie. Phasellus ex lorem, rhoncus in velit vitae, pharetra hendrerit metus. Suspendisse venenatis purus eget auctor sollicitudin. Phasellus ligula velit, pharetra non odio id, vestibulum ullamcorper tellus. Donec non auctor nisl. Ut in elit laoreet, pulvinar erat non, pulvinar est. Cras interdum, sapien id pellentesque commodo, velit orci lobortis orci, nec rhoncus odio dolor at arcu. Phasellus luctus ex non erat aliquam ultrices. Aliquam cursus libero purus, imperdiet finibus nisi consectetur ut. Quisque tincidunt porta pulvinar. Maecenas faucibus lorem id lorem fermentum eleifend. Nunc id malesuada velit. Donec pellentesque augue vel risus ultrices, quis dapibus nunc porta. Nullam sagittis eleifend arcu ac tincidunt. In a posuere nunc. Mauris tristique sagittis libero, non efficitur felis semper consequat. Aliquam eget interdum dui. Nam mattis bibendum imperdiet. Ut consequat erat vitae eros molestie consectetur. Morbi molestie convallis malesuada. Aenean consectetur sem ac fermentum hendrerit. Suspendisse sed sodales ligula.   Ut ac elit leo. Aliquam et elit nec neque pretium eleifend. Proin vestibulum orci sit amet ex pulvinar efficitur. Aenean et metus volutpat, consequat massa quis, pharetra metus. Donec ipsum nulla, rhoncus ullamcorper ligula ac, pellentesque lacinia nisl. Integer purus arcu, fringilla id feugiat ut, luctus vel nunc. Mauris erat felis, faucibus sed quam at, luctus elementum magna. Aenean a tristique felis. Proin ac placerat ligula. Ut facilisis venenatis nulla quis interdum. Phasellus ullamcorper porta aliquam. Donec consectetur pretium mauris, nec gravida purus. Cras bibendum purus non nunc feugiat, ut tristique dolor condimentum.
                Sed in pellentesque massa, quis eleifend libero. Sed placerat ullamcorper neque, quis tempus erat iaculis sit amet. Nullam ipsum ipsum, sagittis eget magna quis, vehicula blandit felis. Donec malesuada lacus vel erat mattis, non tempor sapien tempus. Sed vitae odio velit. Proin aliquam massa ac ante rhoncus sollicitudin. Cras vitae nibh non quam lacinia pharetra quis at neque. Nullam id posuere urna, at hendrerit nulla. Morbi feugiat vehicula dapibus. Cras iaculis ex a ante condimentum aliquet. Morbi ac rutrum dolor.
                Cras eget neque tempus nisl porta finibus vel vel augue. Proin purus diam, sodales eu vestibulum at, mollis interdum erat. Duis molestie ipsum arcu, commodo sodales diam accumsan vitae. Proin ut aliquam sem. Sed aliquet mattis arcu at sagittis. Morbi ac nisi vel nisl varius laoreet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas turpis nulla, finibus eu enim cursus, porttitor facilisis nibh.
            </p>
        </Page>
    );
};

export default Home;